package hospital;
// Generated Feb 23, 2016 10:54:10 PM by Hibernate Tools 4.3.1



/**
 * InPatientId generated by hbm2java
 */
public class InPatientId  implements java.io.Serializable {


     private String inPatientNo;
     private String wardWardNo;
     private String localDoctorClinicNo;
     private String patientMedicationInPatientNo;

    public InPatientId() {
    }

    public InPatientId(String inPatientNo, String wardWardNo, String localDoctorClinicNo, String patientMedicationInPatientNo) {
       this.inPatientNo = inPatientNo;
       this.wardWardNo = wardWardNo;
       this.localDoctorClinicNo = localDoctorClinicNo;
       this.patientMedicationInPatientNo = patientMedicationInPatientNo;
    }
   
    public String getInPatientNo() {
        return this.inPatientNo;
    }
    
    public void setInPatientNo(String inPatientNo) {
        this.inPatientNo = inPatientNo;
    }
    public String getWardWardNo() {
        return this.wardWardNo;
    }
    
    public void setWardWardNo(String wardWardNo) {
        this.wardWardNo = wardWardNo;
    }
    public String getLocalDoctorClinicNo() {
        return this.localDoctorClinicNo;
    }
    
    public void setLocalDoctorClinicNo(String localDoctorClinicNo) {
        this.localDoctorClinicNo = localDoctorClinicNo;
    }
    public String getPatientMedicationInPatientNo() {
        return this.patientMedicationInPatientNo;
    }
    
    public void setPatientMedicationInPatientNo(String patientMedicationInPatientNo) {
        this.patientMedicationInPatientNo = patientMedicationInPatientNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InPatientId) ) return false;
		 InPatientId castOther = ( InPatientId ) other; 
         
		 return ( (this.getInPatientNo()==castOther.getInPatientNo()) || ( this.getInPatientNo()!=null && castOther.getInPatientNo()!=null && this.getInPatientNo().equals(castOther.getInPatientNo()) ) )
 && ( (this.getWardWardNo()==castOther.getWardWardNo()) || ( this.getWardWardNo()!=null && castOther.getWardWardNo()!=null && this.getWardWardNo().equals(castOther.getWardWardNo()) ) )
 && ( (this.getLocalDoctorClinicNo()==castOther.getLocalDoctorClinicNo()) || ( this.getLocalDoctorClinicNo()!=null && castOther.getLocalDoctorClinicNo()!=null && this.getLocalDoctorClinicNo().equals(castOther.getLocalDoctorClinicNo()) ) )
 && ( (this.getPatientMedicationInPatientNo()==castOther.getPatientMedicationInPatientNo()) || ( this.getPatientMedicationInPatientNo()!=null && castOther.getPatientMedicationInPatientNo()!=null && this.getPatientMedicationInPatientNo().equals(castOther.getPatientMedicationInPatientNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInPatientNo() == null ? 0 : this.getInPatientNo().hashCode() );
         result = 37 * result + ( getWardWardNo() == null ? 0 : this.getWardWardNo().hashCode() );
         result = 37 * result + ( getLocalDoctorClinicNo() == null ? 0 : this.getLocalDoctorClinicNo().hashCode() );
         result = 37 * result + ( getPatientMedicationInPatientNo() == null ? 0 : this.getPatientMedicationInPatientNo().hashCode() );
         return result;
   }   


}


