package hospital;
// Generated Feb 23, 2016 10:54:10 PM by Hibernate Tools 4.3.1



/**
 * PatientAppointmentId generated by hbm2java
 */
public class PatientAppointmentId  implements java.io.Serializable {


     private int appNo;
     private String staffStaffNo;
     private String outPatientOutPatientNo;

    public PatientAppointmentId() {
    }

    public PatientAppointmentId(int appNo, String staffStaffNo, String outPatientOutPatientNo) {
       this.appNo = appNo;
       this.staffStaffNo = staffStaffNo;
       this.outPatientOutPatientNo = outPatientOutPatientNo;
    }
   
    public int getAppNo() {
        return this.appNo;
    }
    
    public void setAppNo(int appNo) {
        this.appNo = appNo;
    }
    public String getStaffStaffNo() {
        return this.staffStaffNo;
    }
    
    public void setStaffStaffNo(String staffStaffNo) {
        this.staffStaffNo = staffStaffNo;
    }
    public String getOutPatientOutPatientNo() {
        return this.outPatientOutPatientNo;
    }
    
    public void setOutPatientOutPatientNo(String outPatientOutPatientNo) {
        this.outPatientOutPatientNo = outPatientOutPatientNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientAppointmentId) ) return false;
		 PatientAppointmentId castOther = ( PatientAppointmentId ) other; 
         
		 return (this.getAppNo()==castOther.getAppNo())
 && ( (this.getStaffStaffNo()==castOther.getStaffStaffNo()) || ( this.getStaffStaffNo()!=null && castOther.getStaffStaffNo()!=null && this.getStaffStaffNo().equals(castOther.getStaffStaffNo()) ) )
 && ( (this.getOutPatientOutPatientNo()==castOther.getOutPatientOutPatientNo()) || ( this.getOutPatientOutPatientNo()!=null && castOther.getOutPatientOutPatientNo()!=null && this.getOutPatientOutPatientNo().equals(castOther.getOutPatientOutPatientNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAppNo();
         result = 37 * result + ( getStaffStaffNo() == null ? 0 : this.getStaffStaffNo().hashCode() );
         result = 37 * result + ( getOutPatientOutPatientNo() == null ? 0 : this.getOutPatientOutPatientNo().hashCode() );
         return result;
   }   


}


