package hospital;
// Generated Feb 23, 2016 10:54:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private String staffNo;
     private String lastName;
     private String firstName;
     private String streetName;
     private String houseNumber;
     private String city;
     private String cellphoneNo;
     private Date dateOfBirth;
     private String sex;
     private String positionHeld;
     private Double currentSalary;
     private Set wardRequisitions = new HashSet(0);
     private Set patientAppointments = new HashSet(0);

    public Staff() {
    }
    
    public Staff(String staffNo) {
        this.staffNo = staffNo;
    }
    public Staff(String staffNo, String lastName, String firstName, String streetName, String houseNumber, String city, String cellphoneNo, Date dateOfBirth, String sex, String positionHeld, Double currentSalary, Set wardRequisitions, Set patientAppointments) {
       this.staffNo = staffNo;
       this.lastName = lastName;
       this.firstName = firstName;
       this.streetName = streetName;
       this.houseNumber = houseNumber;
       this.city = city;
       this.cellphoneNo = cellphoneNo;
       this.dateOfBirth = dateOfBirth;
       this.sex = sex;
       this.positionHeld = positionHeld;
       this.currentSalary = currentSalary;
       this.wardRequisitions = wardRequisitions;
       this.patientAppointments = patientAppointments;
    }
    public String getStaffNo() {
        return this.staffNo;
    }
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo;
    }
    public String getLastName() {
        return this.lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getStreetName() {
        return this.streetName;
    }
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public String getHouseNumber() {
        return this.houseNumber;
    }
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }
    public String getCity() {
        return this.city;
    }
    public void setCity(String city) {
        this.city = city;
    }
    public String getCellphoneNo() {
        return this.cellphoneNo;
    }
    public void setCellphoneNo(String cellphoneNo) {
        this.cellphoneNo = cellphoneNo;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getSex() {
        return this.sex;
    }
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getPositionHeld() {
        return this.positionHeld;
    }
    public void setPositionHeld(String positionHeld) {
        this.positionHeld = positionHeld;
    }
    public Double getCurrentSalary() {
        return this.currentSalary;
    }
    public void setCurrentSalary(Double currentSalary) {
        this.currentSalary = currentSalary;
    }
    public Set getWardRequisitions() {
        return this.wardRequisitions;
    }
    public void setWardRequisitions(Set wardRequisitions) {
        this.wardRequisitions = wardRequisitions;
    }
    public Set getPatientAppointments() {
        return this.patientAppointments;
    }
    public void setPatientAppointments(Set patientAppointments) {
        this.patientAppointments = patientAppointments;
    }




}


