package hospital;
// Generated Feb 23, 2016 10:54:10 PM by Hibernate Tools 4.3.1



/**
 * WardRequisitionId generated by hbm2java
 */
public class WardRequisitionId  implements java.io.Serializable {


     private String requisitionNo;
     private String staffStaffNo;
     private String wardWardNo;

    public WardRequisitionId() {
    }

    public WardRequisitionId(String requisitionNo, String staffStaffNo, String wardWardNo) {
       this.requisitionNo = requisitionNo;
       this.staffStaffNo = staffStaffNo;
       this.wardWardNo = wardWardNo;
    }
   
    public String getRequisitionNo() {
        return this.requisitionNo;
    }
    
    public void setRequisitionNo(String requisitionNo) {
        this.requisitionNo = requisitionNo;
    }
    public String getStaffStaffNo() {
        return this.staffStaffNo;
    }
    
    public void setStaffStaffNo(String staffStaffNo) {
        this.staffStaffNo = staffStaffNo;
    }
    public String getWardWardNo() {
        return this.wardWardNo;
    }
    
    public void setWardWardNo(String wardWardNo) {
        this.wardWardNo = wardWardNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WardRequisitionId) ) return false;
		 WardRequisitionId castOther = ( WardRequisitionId ) other; 
         
		 return ( (this.getRequisitionNo()==castOther.getRequisitionNo()) || ( this.getRequisitionNo()!=null && castOther.getRequisitionNo()!=null && this.getRequisitionNo().equals(castOther.getRequisitionNo()) ) )
 && ( (this.getStaffStaffNo()==castOther.getStaffStaffNo()) || ( this.getStaffStaffNo()!=null && castOther.getStaffStaffNo()!=null && this.getStaffStaffNo().equals(castOther.getStaffStaffNo()) ) )
 && ( (this.getWardWardNo()==castOther.getWardWardNo()) || ( this.getWardWardNo()!=null && castOther.getWardWardNo()!=null && this.getWardWardNo().equals(castOther.getWardWardNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRequisitionNo() == null ? 0 : this.getRequisitionNo().hashCode() );
         result = 37 * result + ( getStaffStaffNo() == null ? 0 : this.getStaffStaffNo().hashCode() );
         result = 37 * result + ( getWardWardNo() == null ? 0 : this.getWardWardNo().hashCode() );
         return result;
   }   


}


