package hospital;
// Generated Feb 23, 2016 10:54:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WardRequisition generated by hbm2java
 */
public class WardRequisition  implements java.io.Serializable {


     private WardRequisitionId id;
     private Staff staff;
     private Ward ward;
     private String drugNo;
     private String description;
     private String dosage;
     private String methodOfAdmin;
     private Integer quatity;
     private Date dateOrdered;

    public WardRequisition() {
    }

	
    public WardRequisition(WardRequisitionId id, Staff staff, Ward ward) {
        this.id = id;
        this.staff = staff;
        this.ward = ward;
    }
    public WardRequisition(WardRequisitionId id, Staff staff, Ward ward, String drugNo, String description, String dosage, String methodOfAdmin, Integer quatity, Date dateOrdered) {
       this.id = id;
       this.staff = staff;
       this.ward = ward;
       this.drugNo = drugNo;
       this.description = description;
       this.dosage = dosage;
       this.methodOfAdmin = methodOfAdmin;
       this.quatity = quatity;
       this.dateOrdered = dateOrdered;
    }
   
    public WardRequisitionId getId() {
        return this.id;
    }
    
    public void setId(WardRequisitionId id) {
        this.id = id;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Ward getWard() {
        return this.ward;
    }
    
    public void setWard(Ward ward) {
        this.ward = ward;
    }
    public String getDrugNo() {
        return this.drugNo;
    }
    
    public void setDrugNo(String drugNo) {
        this.drugNo = drugNo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDosage() {
        return this.dosage;
    }
    
    public void setDosage(String dosage) {
        this.dosage = dosage;
    }
    public String getMethodOfAdmin() {
        return this.methodOfAdmin;
    }
    
    public void setMethodOfAdmin(String methodOfAdmin) {
        this.methodOfAdmin = methodOfAdmin;
    }
    public Integer getQuatity() {
        return this.quatity;
    }
    
    public void setQuatity(Integer quatity) {
        this.quatity = quatity;
    }
    public Date getDateOrdered() {
        return this.dateOrdered;
    }
    
    public void setDateOrdered(Date dateOrdered) {
        this.dateOrdered = dateOrdered;
    }




}


